export const defaultProductData = {
  etc: {
    earlyRedemptionFee: '',
    etcNode: '',
    joinMethod: '',
    primeCondition: '',
    provider: '',
    userOffice: '',
    divisionOffice: '',
  },
  loan: {
    baseRate: '',
    gracePeriod: '',
    loanLimit: '',
    loanName: '',
    rate: '',
    repayMethod: '',
    repayPeriod: '',
    overdueRate: '',
    usge: '',
    wholePeriod: '',
  },
  target: {
    age: '',
    area: '',
    creditScore: '',
    income: '',
    loanDescription: '',
    loanTarget: '',
  },
};
